DROP DATABASE IF EXISTS Testapp;

CREATE DATABASE Testapp;

USE Testapp;

CREATE TABLE USER
(
  USERID BIGINT NOT NULL,
  USERFIRSTNAME VARCHAR(256),
  USERLASTNAME VARCHAR(256)
) ENGINE = InnoDB;

INSERT INTO USER (USERID, USERFIRSTNAME, USERLASTNAME)
VALUES ('1','Navya','pat');
  
